FROM python:3.11-slim

RUN apt-get update && apt-get install -y curl ca-certificates && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Dependências dos serviços
COPY app/gateway/requirements.txt /app/gateway_requirements.txt
COPY app/storage/requirements.txt /app/storage_requirements.txt
RUN pip install --no-cache-dir -r /app/gateway_requirements.txt &&     pip install --no-cache-dir -r /app/storage_requirements.txt

# Código e testes
COPY app/gateway /app/gateway
COPY app/storage /app/storage
COPY app/tests /app/tests
COPY pytest.ini /app/pytest.ini

CMD ["pytest", "tests", "--cov=gateway", "--cov=storage", "--cov-report=term-missing", "--cov-fail-under=89"]
